services:
  mongodb:
    image: mongo:7
    container_name: logview-mongodb
    ports:
      - "27017:27017"
    volumes:
      - logview-mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: logview

volumes:
  logview-mongo-data:
